

services:
  php-apache:
    build: 
      context: ./docker
    container_name: file_manager_php
    ports:
      - "8080:80" # Map port 8080 on the host to port 80 in the container
    volumes:
      - .:/var/www/html
    environment:
      - APACHE_RUN_USER=www-data
      - APACHE_RUN_GROUP=www-data
    depends_on:
      - db
    restart: always

  db:
    image: postgres:12
    container_name: file_manager_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: y@suk321
      POSTGRES_DB: idkdb
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: always

volumes:
  postgres_data:
